# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: pool
    type: object
    default:
      vmImage: ubuntu-22.04
  - name: arch
    type: string
    default: amd64
  - name: image
    type: string
    # default: publicmirror.azurecr.io/debian:trixie
    # default: sonicdev-microsoft.azurecr.io/sonic-slave-trixie-amd64
    default: sonicdev-microsoft.azurecr.io/sonic-slave-trixie
  - name: buildOthers
    type: boolean
    default: true
  - name: artifactNamePrefix
    type: string
    default: fips-symcrypt-

jobs:
- job: Build${{ parameters.arch }}
  displayName: Build-${{ parameters.arch }}
  timeoutInMinutes: 600
  pool: ${{ parameters.pool }}
  container:
    image: ${{ parameters.image }}
    options:  "--name ci-container -v /usr/bin/docker:/tmp/docker:ro --ulimit nofile=1024:1048576"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: 'Install Sudo in container'
  - script: |
      sudo rm -rf $(ls -A1)
    displayName: 'Clean Workspace'
  - script: |
      set -x
      sudo mkdir -p $HOME
      sudo chown $USER $HOME
      sudo apt-get update
      sudo apt-get install -y git python3-pip
      sudo apt-get install -y cmake git make build-essential quilt debhelper bc python3 python3-pip sudo libssl-dev libgcc-12-dev
      sudo apt-get install -y clang
      sudo apt-get install -y openssl libssl-dev libssl3t64
      sudo apt-get install -y dh-exec dh-runit libaudit-dev libedit-dev libfido2-dev libgtk-3-dev libkrb5-dev
      sudo apt-get install -y libwrap0-dev pkg-config
      sudo apt-get install -y libpam-dev libselinux1-dev libsystemd-dev libwrap0-dev
      sudo apt-get install -y dpkg-dev apt-utils dh-make python3-pyelftools comerr-dev keyutils python3-kdcproxy python3-pyrad debhelper-compat
      sudo apt-get install -y libnss-myhostname pkgconf libwtmpdb-dev libpam0g-dev zlib1g-dev

      # Build Golang
      sudo apt-get install -y golang
 
      # Build Python
      sudo apt-get install -y lsb-release sharutils libreadline-dev libncursesw5-dev  libbz2-dev liblzma-dev libgdbm-dev libdb-dev tk-dev blt-dev  libexpat1-dev libbluetooth-dev locales-all libsqlite3-dev media-types
      sudo apt-get install -y time net-tools xvfb systemtap-sdt-dev python3-sphinx python3-docs-theme texinfo liblmdb-dev

      # Build krb5
      sudo apt-get install -y ss-dev libldap2-dev libc6-dev libkeyutils-dev byacc docbook-to-man libsasl2-dev libverto-dev python3-cheetah python3-lxml doxygen doxygen-latex tex-gyre

      sudo pip3 install --break-system-packages blurb

      sudo apt-get install -y tree

      sudo apt install -f
      mkdir -p $(Pipeline.Workspace)/target
    displayName: 'Install packages'
  - checkout: self
    submodules: true
  - script: |
      cd src/SymCrypt
      git submodule update --init -- 3rdparty/jitterentropy-library
    displayName: 'Checkout Symcrypt submodules'
  - script: |
      set -ex
      sudo mkdir -p $HOME
      sudo pip3 install --break-system-packages -r src/SymCrypt/scripts/requirements.txt
      git config --global user.name sonicbld
      git config --global user.email sonicbld@microsoft.com
      if [ "${{ parameters.arch }}" == armhf ]; then
        ARCH=${{ parameters.arch }} SYMCRYPT_TEST=n make symcrypt
      else
        ARCH=${{ parameters.arch }} make symcrypt
      fi
      sudo dpkg -i target/symcrypt-openssl*.deb
    displayName: 'Build and install symcrypt'
  - script: |
      set -ex
      ARCH=${{ parameters.arch }} make openssl
      sudo dpkg -i target/libssl*.deb target/openssl*.deb
    condition: true
    displayName: 'Build and install openssl'
  - script: |
      set -ex
      sudo mkdir -p /etc/fips
      echo 1 | sudo tee /etc/fips/fips_enable
      echo 40-Modify-tests-with-unsupported-behavior.patch >> src/openssl.patch/series
      openssl engine -v | grep -i symcrypt
      openssl list --providers | grep -i symcrypt
      pushd src/openssl
      git clean -xdf
      git checkout -- .
      popd

      ARCH=${{ parameters.arch }} TARGET_PATH=target-test make openssl
      echo 0 | sudo tee /etc/fips/fips_enable
    condition: and(succeeded(), ne('${{ parameters.arch }}', 'armhf'))
    continueOnError: true
    displayName: 'Test with fips enabled'

  - script: |
      set -ex
      if [ "$(cat /etc/fips/fips_enable)" != "0" ]; then
        cat src/openssl.patch/skipped-openssl-tests.conf
        TESTS=$(cat src/openssl.patch/skipped-openssl-tests.conf | sed 's/^/-/' | xargs)
        pushd src/openssl/build_shared
        make TESTS="$TESTS" test
        popd
        echo 0 | sudo tee /etc/fips/fips_enable
      fi
    condition: and(succeeded(), ne('${{ parameters.arch }}', 'armhf'))
    displayName: 'Test and skip known issues'
 
  - script: |
      set -ex
      git config --global user.email sonicbld@microsoft.com
      git config --global user.name mssonicbld
      ARCH=${{ parameters.arch }} make all
      cp src/*.deb target/
    condition: and(succeeded(), ${{ eq(parameters.buildOthers, true) }})
    displayName: 'Build others'
  - publish: $(System.DefaultWorkingDirectory)/target
    artifact: ${{ parameters.artifactNamePrefix }}${{ parameters.arch }}
    displayName: "Archive packages"
  - publish:  $(Build.ArtifactStagingDirectory)
    condition: failed()
    artifact: '${{ parameters.artifactNamePrefix }}${{ parameters.arch }}-(System.JobAttempt)'
    displayName: "Archive failed packages"
